### ISSUE TITLE
changelog please

### ISSUE THREAD

**Issue by onlyjob** [odrevet/video-without-flash-restartless#10]
It would be useful to have `NEWS` or `changelog` file with plain text contents similar to 

https://addons.mozilla.org/en-US/firefox/addon/video-without-flash/versions/

Thanks.

**Comment by odrevet** [comment]
Is the tag release page
<https://github.com/odrevet/video-without-flash-restartless/releases>adequats
?
If not I can create the changelog file


2015-04-15 10:36 GMT+02:00 Dmitry Smirnov <notifications@github.com>:

**Comment by onlyjob** [comment]
It's just that changelog is not in the tarball... Debian package is made from tarball which is semi-automatically downloaded from release page. If changelog were committed it would be possible to integrate it into packaging...

**Comment by odrevet** [comment]
I understand, I commited ChangeLog
tell me if the format suits .

2015-04-15 10:58 GMT+02:00 Dmitry Smirnov <notifications@github.com>:

**Comment by onlyjob** [comment]
Perfect, thank you. :)

Format is similar to [GNU changelog format](http://www.gnu.org/prep/standards/html_node/Change-Logs.html) and looking good.

**Comment by odrevet** [comment]
Yes I RTFM for once :)

**Comment by onlyjob** [comment]
:-) :)
