### ISSUE TITLE
Facebook videos support

### ISSUE THREAD

**Issue by mightyiam** [odrevet/video-without-flash-restartless#3]
Do you see a possibility for that, technically, please?

**Comment by mightyiam** [comment]
Does this mean no?

**Comment by onlyjob** [comment]
I also feel confused when bugs are closed without comment. Is it "fixed" or "wontfix/rejected" or "invalid"?

**Comment by odrevet** [comment]
I won't make a facebook video parser because I don't have a facebook account or have any intention to create one. I've reopen this issue in case someone would take it.

**Comment by eMBee** [comment]
some facebook pages are public and can be accessed without login. here for example:
https://www.facebook.com/STBEYOND
