### ISSUE TITLE
youtube: video format detection problems; video reload problem.

### ISSUE THREAD

**Issue by onlyjob** [odrevet/video-without-flash-restartless#5]
Debian user reported format detection problems on Youtube, please see details on the following page: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=772421
Although reported for version 1.5.0 it seems that version 2.0.0 may be affected as well.

In regards to youtube video format detection may be [youtube-dl](https://rg3.github.io/youtube-dl/) can provide some inspiration?

Besides I've noticed that once video-without-flash is activated on youtube, clicking other videos do not reload embedded video. Am I missing something?

Thanks.

**Comment by SamB** [comment]
@odrevet Until such time as you remove the youtube stuff entirely, perhaps you should make it easier to tell when VWOF is attempting to operate on a given page?  It took me a while to figure out that it was why I couldn't get <https://www.youtube.com/watch?v=8Gv0H-vPoDc> to play, regardless of whether I chose the default player or the html5 one, and whether I had MSE enabled or not.

User-Agent:  Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.5.0

Package version: 31.5.0esr-1~deb7u1

**Comment by onlyjob** [comment]
According to [changelog](https://addons.mozilla.org/en-US/firefox/addon/video-without-flash/versions/) youtube module is removed but apparently the module is still here: [youtube.jsm](../blob/master/content/modules/youtube.jsm).

Besides YouTube is still mentioned in [README.md](../blob/master/README.md)...

**Comment by odrevet** [comment]
The youtube module is now removed. Thanks for reporting
